<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container06lnxdt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container06lnxdt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container06lnxdt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container06lnxdt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container06lnxdt\App_KernelDevDebugContainer([
    'container.build_hash' => '06lnxdt',
    'container.build_id' => 'f8cf6197',
    'container.build_time' => 1770311464,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container06lnxdt');
