<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_api_centre_index' => [[], ['_controller' => 'App\\Controller\\Api\\CentreController::index'], [], [['text', '/api/centre']], [], [], []],
    'app_api_demande' => [[], ['_controller' => 'App\\Controller\\Api\\DemandeController::index'], [], [['text', '/api/demande']], [], [], []],
    'app_api_region_index' => [[], ['_controller' => 'App\\Controller\\Api\\RegionController::index'], [], [['text', '/api/region']], [], [], []],
    'App\Controller\Api\CentreController::index' => [[], ['_controller' => 'App\\Controller\\Api\\CentreController::index'], [], [['text', '/api/centre']], [], [], []],
    'App\Controller\Api\DemandeController::index' => [[], ['_controller' => 'App\\Controller\\Api\\DemandeController::index'], [], [['text', '/api/demande']], [], [], []],
    'App\Controller\Api\RegionController::index' => [[], ['_controller' => 'App\\Controller\\Api\\RegionController::index'], [], [['text', '/api/region']], [], [], []],
];
